---
title: "BLS Statistical Seminar on Monday, March 28th"
description: |
  Data Analysis after Record Linkage: sources of error, consequences, and possible solutions, Dr. Martin Slawski, Department of Statistics, Volgenau School of Engineering, George Mason University
preview: https://img.vendingmarketwatch.com/files/base/cygnus/vmw/image/2020/09/16x9/US_Bureaw_Labor_Stats_WIKIPEDIA.5f57a9653b517.png
author:
  - name: RLIG
date: 2022-03-22
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

You are invited to the next virtual BLS Statistical Seminar on Monday, March 28th at 2PM via the Teams link below.

### Title

**Data Analysis after Record Linkage: sources of error, consequences, and possible solutions, Dr. Martin Slawski, Department of Statistics, Volgenau School of Engineering, George Mason University**

### Date 
Monday, March 28th, 2022

### Time

2:00PM - 3:30PM EDT

### Location
Microsoft Teams ([click here to join the meeting](https://urldefense.com/v3/__https://nam10.safelinks.protection.outlook.com/ap/t-59584e83/?url=https*3A*2F*2Fteams.microsoft.com*2Fl*2Fmeetup-join*2F19*253ameeting_ODIwYTQ1OGQtOTgyNi00ZDgyLWJmMzktYjNlMjQxZmM5MjQz*2540thread.v2*2F0*3Fcontext*3D*257b*2522Tid*2522*253a*25223b06518d-2bac-4bbf-95d4-d731899ce4e2*2522*252c*2522Oid*2522*253a*25221ac7c198-32cd-4395-8673-f0df95984787*2522*257d&data=04*7C01*7Cjana.asher*40sru.edu*7C862948126ec04c4b76dc08d9fc95e2a8*7C86555dba073b4ff7b7d1b73a77c5bd92*7C0*7C0*7C637818542947844638*7CUnknown*7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0*3D*7C3000&sdata=9LXP5zdkycb3VUgJuJEqw9Zk7SYsSb0QUOoM1BIEp1k*3D&reserved=0__;JSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJSUlJQ!!OToaGQ!7DlgkFfJM2Bo2EH4VwnTW-K1461CilDf9-PdyXORjNDu2VWD7HATOuXjv5iZuLIlLNDwbQ$))

### Speaker

Dr. Martin Slawski, Department of Statistics, Volgenau School of Engineering, George Mason University 

### Abstract

Record linkage bears a lot of opportunities for creating richer data products, saving costs in data collection, reducing respondent burden, and avoiding response bias or measurement error. At the same time, the possibility of linkage error is often unaccounted for. Linkage error arises from uncertainty about which pairs of records residing in two separate files belong to the same statistical unit, and can result into mismatches (false positive matches) and missed matches (false negative matches).

In this talk, we focus on mismatch error and to what extent such error may contaminate downstream data analysis (e.g., regression or principal component analysis), which in turn leads to invalid inferences. We then provide an overview of possible statistical methods that can be applied to mitigate the impact of such errors. We argue that there is no universal strategy for this task; instead, the mitigation method of choice depends on several factors such as the mismatch rate, goodness of fit of the model used by the data analyst, available knowledge about the linkage process, computational resources, and the analysis question (inferential goal, statistical model) of interest.



